import { GoogleGenAI } from '@google/genai';

//This isn't working, find out a way to get this to work. For now, it's just in plain text, yucky
// import dotenv from 'dotenv'
// dotenv.config({path: '../../config.env'});


/**
 * Generate a loading screen quote for when the user is looking for a match
 * @param {String} sport - What sport to generate the quote for
 * @param {String} context - What type of quote you want, e.x fun fact, tip, statistic
* @param {String} key - API key for google
 * @returns {String} String of the quote generated by AI
 * 
 * Make sure to wrap this in a try catch incase it returns an error for quota overflow
*/
export async function getLoadingQuote(sport, context, key) {
  
  const ai = new GoogleGenAI({ apiKey: key });

  const response = await ai.models.generateContent({
    model: "gemini-2.0-flash",
    contents: `Give me a random true one line ${context} about ${sport}`,
    temperature: 100,
  });
  return response.text
}


async function main() {
  x = await getLoadingQuote('tennis','tip')
  console.log(x);
}


