import GoogleGenAI from '@google/genai';
import dotenv from 'dotenv'
dotenv.config({path: './config.env'});

const ai = new GoogleGenAI.GoogleGenAI({ apiKey: process.env.AI_URI });

/**
 * Generate a loading screen quote for when the user is looking for a match
 * @param {String} sport - What sport to generate the quote for
 * @param {String} context - What type of quote you want, e.x fun fact, tip, statistic
 * @returns {String} String of the quote generated by AI
 * 
 * Make sure to wrap this in a try catch incase it returns an error for quota overflow
 */
export async function getLoadingQuote(sport, context) {

  const response = await ai.models.generateContent({
    model: "gemini-2.0-flash",
    contents: `Give me a random true one line ${context} about ${sport}`,
    temperature: 100,
  });
  return response.text
}


async function main() {
  x = await getLoadingQuote('tennis','tip')
  console.log(x);
}


